deploy:
  stage: deploy
  script:
    - echo "all done"
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  variables:
    API_TOKEN: $TEST_DEPLOYMENT_TOKEN
    APP_PATH: '$CI_PROJECT_DIR'
    API_PATH: ''
    OUTPUT_PATH: 'out'
    REDIRECT_URI: 'https://thankful-dune-0fbe9e810.1.azurestaticapps.net/login/'
    POST_LOGOUT_REDIRECT_URI: 'https://thankful-dune-0fbe9e810.1.azurestaticapps.net/login/'
    REDIRECT_URI_INVITATION: 'https://thankful-dune-0fbe9e810.1.azurestaticapps.net/signup/'
    SIGNIN_POLICY: 'https://speechmaticsb2c.b2clogin.com/speechmaticsb2c.onmicrosoft.com/B2C_1A_SIGNIN_ONLY'
    INVITATION_SIGNUP_POLICY: 'https://speechmaticsb2c.b2clogin.com/speechmaticsb2c.onmicrosoft.com/B2C_1A_SIGNUP_INVITATION'
    RESET_PASSWORD_POLICY: 'https://speechmaticsb2c.b2clogin.com/speechmaticsb2c.onmicrosoft.com/B2C_1A_PASSWORDRESET'
    AUTHORITY_DOMAIN: 'speechmaticsb2c.b2clogin.com'
    POLICY_DOMAIN: 'speechmaticsb2c.onmicrosoft.com'
    AUTH_CLIENT_ID: '75a2952e-954e-4975-8a14-ef862a8e5a39'
    ENDPOINT_API_URL: 'https://speechmatics-mp-dev-ingress-a.westeurope.cloudapp.azure.com/v1'
    TEST_API_CALL_ENDPOINT: 'https://self-service-chargify-poc.azurewebsites.net/hello'
    DEFAULT_B2C_SCOPE: 'https://speechmaticsb2c.onmicrosoft.com/michaltestapi/User.Read'
    CHARGIFY_PUBLIC_KEY: 'chjs_dv9b2hv745b3dc5knfkddy64'
    CHARGIFY_SERVER_HOST: 'https://speechmatics-staging.chargify.com'
    TEST_ENV: "my env test is here"
  only:
    - ci-test
